apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx
  labels:
    app: testnginx
spec:
  selector:
    matchLabels:
      app: testnginx
  replicas: 2
  template:
    metadata:
      labels:
        app: testnginx
    spec:
      containers:
      - name: testnginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet: 
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 1
        ports:
        - containerPort: 80
