apiVersion: v1
kind: Pod
metadata:
    name: testnginx
spec:
  containers:
  - name: test-nginx
    image: nginx:alpine
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5 
      failureThreshold: 1
      
