apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cluster-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: cluster-storage
spec: 
  capacity: 
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  storageClassName: cluster-storage
  local: 
    path: /persistVolumes/mssql1/
  nodeAffinity: 
    required: 
      nodeSelectorTerms: 
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: 
            - k4hrl-worker01
